# Default values for gso-webapp-webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 3
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
image:
  repository: 026111650332.dkr.ecr.us-east-1.amazonaws.com/gso-webapp
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev-5a49e36"
imagePullSecrets:
  - name: svm-ecr-registry
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
env: []
ports:
  - name: main-port
    containerPort: 3001
    protocol: TCP
  - name: liveness-port
    containerPort: 3001
    protocol: TCP
# HealCheck
probes:
  enabled: false
  startupProbe:
    httpGet:
      path: /api/v1/health/kube-startup
      port: liveness-port
      httpHeaders:
        - name: Accept
          value: application/json
    timeoutSeconds: 3
    failureThreshold: 3
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /api/v1/health/kube-liveness
      port: liveness-port
      httpHeaders:
        - name: Accept
          value: application/json
    timeoutSeconds: 3
    failureThreshold: 1
    #    periodSeconds: 10 (production)
    periodSeconds: 90
  readinessProbe:
    httpGet:
      path: /api/v1/health/kube-readiness
      port: liveness-port
      httpHeaders:
        - name: Accept
          value: application/json
    initialDelaySeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
    #    periodSeconds: 10 (production)
    periodSeconds: 90
# Config map sharing
configmapVolume:
  enabled: false
# service config
service:
  name: main-port
  type: ClusterIP
  port: 80
  targetPort: 3001
ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: kops.k8s.io/instancepay
              operator: In
              values:
                - node-spot
