apiVersion: v1
kind: Service
metadata:
  name: { { include "gso-webapp.fullname" . } }
  labels: { { - include "gso-webapp.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
      protocol: TCP
      name: { { .Values.service.name } }
  selector: { { - include "gso-webapp.selectorLabels" . | nindent 4 } }
